"""GitHub publication through gh, with durable intent and marker reconciliation."""
import json
import logging
import time
from pathlib import Path

from config import Failure
from repos import git
from runtime import command, redact

LOG = logging.getLogger("auto-test")


def marker(report_id):
    return f"<!-- auto-test:{report_id} -->"


def header(provider):
    return f"## 🤖 Generated by <{'Claude' if provider == 'claude' else 'Codex'}>\n\n"


def authors(settings):
    return "; ".join(f"{stage}: {a['provider']} / {a['model']} / {a['reasoning_effort']}" for stage, a in settings["agents"].items())


def finding_body(run_id, sha, finding, verification, checks, settings, report_id, fix=None):
    body = header(settings["agents"]["investigation"]["provider"])
    body += f"{finding['title']}\n\nTested commit: `{sha}`. Run: `{run_id}`. Finding: `{report_id}`.\n\n"
    body += f"Expected: {finding['expected']}\n\nObserved: {finding['actual']}\n\nImpact: {finding['impact']}\n\nReproduction:\n{finding['reproduction']}\n\n"
    if fix:
        body += f"Fix: {fix['summary']}\n\nRegression test: {fix['regression_test']}\n\n"
    body += "Recorded command evidence:\n\n"
    for check in checks[:12]:
        # Publish selected, bounded excerpts, never an entire agent transcript.
        excerpt = Path(check["log"]).read_text(errors="replace")[:1200].replace("```", "'''")
        argv = json.dumps(check["command"], ensure_ascii=False)
        body += f"- {check['phase']}, commit `{check['sha']}`, exit {check['exit_code']}: `{argv.replace('`', chr(39))}`\n\n```text\n{excerpt}\n```\n\n"
    body += f"Verification: {verification['reason']}\n\nRemaining work/decisions: {finding['decision'] or 'None identified.'}\n\nLimitations: {verification['limitations'] or 'Limited to the checks described above.'}\n\n"
    if fix and fix["limitations"]:
        body += f"Patch limitations: {fix['limitations']}\n\n"
    body += f"Agents: {authors(settings)}\n\n{marker(report_id)}\n"
    return redact(body)


def blocker_body(run_id, repository, blocker, settings, report_id):
    return redact(header(settings["agents"]["investigation"]["provider"]) +
        f"Testing `{repository}` is blocked. Run: `{run_id}`.\n\n"
        f"Capability: {blocker['capability']}\n\nCategory: {blocker['category']}\n\n"
        f"Observed: {blocker['error']}\n\nOwner action: {blocker['owner_action']}\n\n"
        f"Agents: {authors(settings)}\n\n{marker(report_id)}\n")


class GitHub:
    def check(self, repository):
        command(["gh", "auth", "status", "--hostname", "github.com"])
        data = json.loads(command(["gh", "api", f"repos/{repository}"]).stdout)
        if data.get("full_name", "").lower() != repository.lower():
            raise Failure(f"GitHub repository could not be verified: {repository}")
        permissions = data.get("permissions", {})
        if not permissions.get("push"):
            raise Failure(f"GitHub access for {repository} must permit branches, PRs and issues")
        if not data.get("has_issues", True):
            raise Failure(f"Enable GitHub issues for {repository}")
        return data

    def reports(self, repository):
        # List all issues/PRs, including closed ones; don't depend on search indexing.
        output = command(["gh", "api", "--paginate", "--slurp", f"repos/{repository}/issues?state=all&per_page=100"], limit=16_000_000).stdout
        try:
            pages = json.loads(output)
            return [issue for page in pages for issue in page if "<!-- auto-test:" in (issue.get("body") or "")]
        except (ValueError, TypeError, AttributeError) as exc:
            raise Failure("Invalid or oversized GitHub report listing; publication deferred") from exc

    def main_sha(self, repository):
        return json.loads(command(["gh", "api", f"repos/{repository}/git/ref/heads/main"]).stdout)["object"]["sha"]

    def pr_sha(self, repository, number):
        return json.loads(command(["gh", "pr", "view", str(number), "--repo", repository, "--json", "headRefOid"]).stdout)["headRefOid"]

    def edit(self, report, existing, body_file):
        kind = "pr" if "pull_request" in existing else "issue"
        command(["gh", kind, "edit", str(existing["number"]), "--repo", report["destination"], "--body-file", body_file])
        return existing["html_url"]

    def create(self, report, body_file):
        if report["kind"] == "pr":
            payload = json.loads(report["payload"])
            args = ["gh", "pr", "create", "--repo", report["destination"], "--base", "main", "--head", payload["branch"], "--title", report["title"], "--body-file", body_file]
        else:
            args = ["gh", "issue", "create", "--repo", report["destination"], "--title", report["title"], "--body-file", body_file]
        url = command(args).stdout.strip()
        if not url.startswith(f"https://github.com/{report['destination']}/"):
            raise Failure("GitHub create returned no recognized URL; reconcile on a later invocation")
        return url

    def push(self, report):
        payload = json.loads(report["payload"])
        workspace, branch = payload["workspace"], payload["branch"]
        # Deterministic branch, no force push. A prior ambiguous successful push is OK.
        remote = f"https://github.com/{report['destination']}.git"
        if payload.get("origin"):
            remote = payload["origin"]
        old = git(workspace, "ls-remote", remote, f"refs/heads/{branch}")
        if old:
            if old.split()[0] != payload["patch_sha"]:
                raise Failure("Deterministic fix branch already contains different work; owner review required")
            return
        git(workspace, "push", remote, f"{payload['patch_sha']}:refs/heads/{branch}")


class Publisher:
    def __init__(self, state, github, dry_run=False):
        self.state, self.github, self.dry_run = state, github, dry_run

    def publish(self, repository=None):
        if self.dry_run:
            return
        for report in self.state.pending(repository):
            try:
                self.one(report)
            except (Failure, OSError, ValueError, KeyError) as exc:
                error = redact(str(exc))
                delay = 6 * 3600 if "rate" in error.lower() else 3600
                # Once create intent is durable, failure might mean GitHub wrote it.
                current = self.state.report(report["id"])
                self.state.update_report(report["id"], error=error, next_retry=time.time() + delay, attempts=current["attempts"] + 1)
                LOG.warning("Publication deferred for %s/%s: %s", report["repository"], report["id"], error)

    def one(self, report):
        existing_reports = self.github.reports(report["destination"])
        matches = [r for r in existing_reports if marker(report["id"]) in (r.get("body") or "")]
        existing = next((r for r in matches if r["state"] == "open"), matches[0] if matches else None)
        if existing and existing["state"] != "open":
            self.state.update_report(report["id"], status="closed", url=existing["html_url"], error=None)
            return
        if not existing and report["url"]:
            # Known reports that disappeared (e.g. transferred/deleted) are not recreated.
            self.state.update_report(report["id"], status="closed", error="Previously published report is no longer listed; owner review required")
            return
        if not existing and report["status"] == "uncertain":
            count = report["reconciliations"] + 1
            # Two separated listing passes and a full day for ambiguous writes.
            if count < 2 or time.time() - (report["uncertain_since"] or time.time()) < 86400:
                self.state.update_report(report["id"], reconciliations=count, next_retry=time.time() + 3600)
                return
            self.state.update_report(report["id"], status="pending", reconciliations=count, next_retry=time.time() + 3600)
            return
        payload = json.loads(report["payload"])
        body_file = Path(payload["body_file"])
        body_file.write_text(redact(report["body"]))
        if existing:
            if "pull_request" in existing and (not payload.get("patch_sha") or self.github.pr_sha(report["destination"], existing["number"]) != payload["patch_sha"]):
                self.state.update_report(report["id"], status="deferred", url=existing["html_url"], error="Existing PR head differs from the verified patch; original report preserved, retained candidate needs owner review")
                return
            if "pull_request" not in existing and payload.get("patch_sha"):
                # An existing issue remains the canonical report. Be explicit that
                # the newly verified local candidate has not been published as a PR.
                body_file.write_text(redact(report["body"] + "\nA verified candidate patch is retained in this run's artifacts. This existing issue was reused; no new PR or branch was published.\n"))
            url = self.github.edit(report, existing, body_file)
        else:
            if report["kind"] == "pr":
                if self.github.main_sha(report["destination"]) != payload["sha"]:
                    self.state.update_report(report["id"], status="deferred", error="main advanced; patch retained for revalidation on a fresh run")
                    return
                self.github.push(report)
                if self.github.main_sha(report["destination"]) != payload["sha"]:
                    self.state.update_report(report["id"], status="deferred", error="main advanced during push; branch retained, needs revalidation")
                    return
            self.state.update_report(report["id"], status="uncertain", uncertain_since=time.time(), reconciliations=0)
            url = self.github.create(report, body_file)
        self.state.update_report(report["id"], status="published", url=url, error=None, next_retry=0)
        LOG.info("Published %s: %s", report["id"], url)
