import fcntl
import json
import os
import time
from pathlib import Path
from unittest import mock

from helpers import GOOD_FIX, GOOD_VERIFY, Case, finding, git

INVESTIGATE_FIX = {'actions': [{'do': 'repro'}], 'result': {'findings': [finding()]}}


class PipelineTest(Case):
    def test_seeded_bug_produces_minimal_verified_pr(self):
        self.set_plan(investigation=[{**INVESTIGATE_FIX, 'result': {
            'findings': [finding()], 'coverage': [{'area': 'calc.divide', 'status': 'tested', 'notes': 'repro'}]}}],
            fixing=[GOOD_FIX], verification=[GOOD_VERIFY])
        self.assertEqual(self.run_cli('--once'), 0)
        sha = self.head()
        [run] = self.runs()
        self.assertEqual((run['status'], run['sha']), ('completed', sha))
        self.assertEqual(self.state().checkpoint('owner/calc')['sha'], sha)
        [pr] = self.gh.created('pr')
        self.assertTrue(pr['body'].startswith('## 🤖 Generated by Claude\n'))
        for text in (sha, 'bug observed', 'bug not observed', 'Return None for a zero divisor', '<!-- auto-test:f-'):
            self.assertIn(text, pr['body'])
        remote = self.remotes['owner/calc']
        self.assertEqual(git(remote, 'rev-parse', pr['branch'] + '^'), sha)
        self.assertEqual(git(remote, 'diff', '--name-only', sha, pr['branch']).split(), ['calc.py', 'test_zero.py'])
        self.assertEqual(self.gh.created('issue'), [])
        self.assertNotIn(str(self.tmp), pr['body'])  # Evidence excerpts show <run>/..., not host paths.
        self.assertIn('<run>/workspace/calc.py', pr['body'])
        self.assertEqual(git(remote, 'log', '-1', '--format=%s', pr['branch']),
                         'Fix: divide() raises ZeroDivisionError instead of returning None')
        self.assertEqual([c['stage'] for c in self.calls()], ['investigation', 'fixing', 'verification'])
        self.assertIn('Coverage', self.log())
        run_dir = Path(run['directory'])
        self.assertTrue((run_dir / 'run.json').is_file())
        self.assertFalse((run_dir / 'workspace').exists())
        # Unchanged main: skipped without model calls or duplicate reports.
        self.assertEqual(self.run_cli('--once'), 0)
        self.assertEqual(len(self.calls()), 3)
        self.assertEqual(len(self.gh.created()), 1)
        self.assertIn('unchanged', self.log())

    def test_unsupported_finding_is_not_published(self):
        self.set_plan(investigation=[{'actions': [{'do': 'repro'}], 'result': {'findings': [
            finding(title='Suspicious', component='calc', root_cause='style', disposition='issue')]}}])
        self.assertEqual(self.run_cli('--once'), 0)
        self.assertEqual(self.gh.created(), [])
        self.assertEqual(self.reports(), [])
        self.assertEqual(self.runs()[0]['status'], 'completed')
        self.assertIn('not published', self.log())

    def test_verified_claim_without_evidence_is_not_published(self):
        claim = {'verdict': 'confirmed', 'fix_verdict': 'effective', 'reason': 'trust me', 'checks': [
            {'command': 'x', 'target': 'baseline', 'exit_code': 1, 'bug_observed': True, 'evidence': '/nonexistent',
             'notes': ''},
            {'command': 'x', 'target': 'patched', 'exit_code': 0, 'bug_observed': False, 'evidence': '{workspace}/calc.py',
             'notes': 'inside the disposable workspace'}]}
        self.set_plan(investigation=[INVESTIGATE_FIX], fixing=[GOOD_FIX], verification=[{'result': claim}])
        self.run_cli('--once')
        self.assertEqual(self.gh.created(), [])

    def test_decision_needed_routes_to_monitored_issue(self):
        self.set_plan(investigation=[{'actions': [{'do': 'repro'}], 'result': {'findings': [
            finding(disposition='issue', disposition_reason='Maintainers must choose None or an exception')]}}],
            verification=[{'actions': [{'do': 'verify_issue'}]}])
        self.run_cli('--once')
        self.assertEqual(self.calls('fixing'), [])
        [issue] = self.gh.created('issue')
        self.assertIn(issue, self.gh.items['owner/calc'])
        self.assertTrue(issue['body'].startswith('## 🤖 Generated by Claude\n'))
        self.assertIn('Maintainers must choose', issue['body'])
        self.assertEqual(self.calls('verification')[0]['ctx']['mode'], 'issue')

    def test_unfixable_finding_becomes_issue(self):
        self.set_plan(investigation=[INVESTIGATE_FIX],
                      fixing=[{'result': {'fixed': False, 'explanation': 'Needs an API decision'}}],
                      verification=[{'actions': [{'do': 'verify_issue'}]}])
        self.run_cli('--once')
        [issue] = self.gh.created('issue')
        self.assertIn('Needs an API decision', issue['body'])
        self.assertEqual(self.gh.created('pr'), [])

    def test_ineffective_fix_gets_one_correction_attempt(self):
        ineffective = {'result': {'verdict': 'confirmed', 'fix_verdict': 'ineffective', 'reason': 'still crashes'}}
        self.set_plan(investigation=[INVESTIGATE_FIX], fixing=[GOOD_FIX], verification=[ineffective, GOOD_VERIFY])
        self.run_cli('--once')
        fixes = self.calls('fixing')
        self.assertEqual(len(fixes), 2)
        self.assertIsNone(fixes[0]['ctx']['verification_feedback'])
        self.assertTrue(fixes[1]['ctx']['verification_feedback'].endswith('verify-1/result.json'))
        self.assertEqual(len(self.gh.created('pr')), 1)

    def test_independent_findings_get_independent_branches(self):
        second = finding(title='Second bug', component='calc.other', root_cause='other cause')
        self.set_plan(investigation=[{'actions': [{'do': 'repro'}], 'result': {'findings': [finding(), second]}}],
                      fixing=[GOOD_FIX], verification=[GOOD_VERIFY])
        self.run_cli('--once')
        prs = self.gh.created('pr')
        self.assertEqual(len(prs), 2)
        self.assertNotEqual(prs[0]['branch'], prs[1]['branch'])
        for pr in prs:
            self.assertEqual(git(self.remotes['owner/calc'], 'rev-parse', pr['branch'] + '^'), self.head())

    def test_no_findings_are_recorded_locally_only(self):
        self.set_plan(investigation=[{'result': {'coverage': [
            {'area': 'API errors', 'status': 'tested', 'notes': '12 probes'},
            {'area': 'browser flows', 'status': 'skipped', 'notes': 'no UI'}]}}])
        self.assertEqual(self.run_cli('--once'), 0)
        self.assertEqual(self.gh.calls, [])
        run = self.runs()[0]
        self.assertEqual(run['status'], 'completed')
        record = json.loads((Path(run['directory']) / 'run.json').read_text())
        self.assertEqual([c['area'] for c in record['coverage']], ['API errors', 'browser flows'])
        self.assertIn('tested=1 skipped=1', run['summary'])

    def test_blocked_run_reports_to_auto_test_and_retries_then_pauses(self):
        blocker = {'capability': 'docker daemon', 'category': 'missing_tool', 'details': 'docker: command not found',
                   'owner_action': 'Install Docker for the auto-test user'}
        self.set_plan(investigation=[{'result': {'outcome': 'blocked', 'blockers': [blocker]}}])
        self.assertEqual(self.run_cli('--once'), 1)
        [issue] = self.gh.created('issue')
        self.assertIn(issue, self.gh.items['owner/auto-test'])
        self.assertIn('owner/calc', issue['body'])
        self.assertIn('Install Docker', issue['body'])
        self.assertEqual(self.runs()[0]['status'], 'blocked')
        self.assertIsNone(self.state().checkpoint('owner/calc'))
        self.run_cli('--once')  # Blocked runs retry without a new commit; the blocker is not duplicated.
        self.run_cli('--once')
        self.assertEqual(len(self.calls('investigation')), 3)
        self.run_cli('--once')
        self.assertEqual(len(self.calls('investigation')), 3)
        self.assertIn('paused', self.log())
        titles = sorted(i['title'] for i in self.gh.created('issue'))
        self.assertEqual(titles, ['Setup blocker: docker daemon', 'Setup blocker: repeated run failures'])

    def test_partial_run_keeps_findings_and_reports_blocker(self):
        blocker = {'capability': 'kubernetes test target', 'category': 'test_target', 'details': 'no namespace',
                   'owner_action': 'Configure test_environment.allowed_targets'}
        self.set_plan(investigation=[{'actions': [{'do': 'repro'}], 'result': {
            'findings': [finding(disposition='issue')], 'blockers': [blocker]}}],
            verification=[{'actions': [{'do': 'verify_issue'}]}])
        self.run_cli('--once')
        self.assertEqual(self.runs()[0]['status'], 'partial')
        self.assertEqual(self.state().checkpoint('owner/calc')['sha'], self.head())
        self.assertEqual(len(self.gh.items['owner/calc']), 1)
        self.assertEqual(len(self.gh.items['owner/auto-test']), 1)

    def test_secrets_are_redacted_from_publication_and_logs(self):
        secret = 's3cr3t-fixture-value-42'
        leaky = finding(disposition='issue', actual=f'server echoed token {secret}')
        self.set_plan(investigation=[{'actions': [{'do': 'repro'}, {'do': 'shell', 'cmd':
                                                  'echo "token=$FIXTURE_TOKEN" >> {evidence_directory}/repro-baseline.txt'}],
                                      'result': {'findings': [leaky], 'summary': f'saw {secret}'}}],
                      verification=[{'actions': [{'do': 'verify_issue'}]}])
        with mock.patch.dict(os.environ, {'FIXTURE_TOKEN': secret}):
            self.run_cli('--once', repositories=[{'name': 'owner/calc', 'test_environment': {
                'description': 'fixture', 'credential_environment_variables': ['FIXTURE_TOKEN']}}])
        self.assertIn('FIXTURE_TOKEN', self.calls('investigation')[0]['env'])
        [issue] = self.gh.created('issue')
        self.assertNotIn(secret, issue['body'])
        self.assertIn('[REDACTED]', issue['body'])
        self.assertNotIn(secret, self.log())


class SelectionTest(Case):
    def test_changes_after_missed_nights_are_listed(self):
        self.run_cli('--once')
        first = self.head()
        self.commit('owner/calc', message='first change')
        self.commit('owner/calc', message='second change')
        self.run_cli('--once')
        ctx = self.calls('investigation')[1]['ctx']
        self.assertEqual(ctx['changes']['mode'], 'incremental')
        self.assertIn('first change', ctx['changes']['excerpt'])
        self.assertIn('second change', ctx['changes']['excerpt'])
        self.assertIn(first, ctx['changes']['excerpt'])
        self.assertEqual(self.calls('investigation')[0]['ctx']['changes']['mode'], 'first-run')

    def test_rewritten_history_investigates_snapshot(self):
        self.run_cli('--once')
        upstream = self.upstreams['owner/calc']
        git(upstream, 'checkout', '-q', '--orphan', 'rewrite')
        git(upstream, 'commit', '-q', '-m', 'rewritten root')
        git(upstream, 'push', '-q', '--force', 'origin', 'rewrite:main')
        self.run_cli('--once')
        self.assertEqual(self.calls('investigation')[1]['ctx']['changes']['mode'], 'history-rewritten')

    def test_missing_main_is_a_configuration_blocker(self):
        self.add_repo('owner/legacy', branch='master')
        self.run_cli('--once')
        self.assertEqual([c['ctx']['repository'] for c in self.calls()], ['owner/calc'])
        [issue] = self.gh.items['owner/auto-test']
        self.assertIn('main branch missing', issue['title'])
        self.assertIn('owner/legacy', issue['body'])

    def test_run_is_pinned_while_main_advances(self):
        upstream = self.upstreams['owner/calc']
        push = (f'cd {upstream} && echo "# moved" >> calc.py && git -c user.name=t -c user.email=t@e '
                'commit -qam moved && git push -q origin HEAD:main')
        pinned = self.head()
        self.set_plan(investigation=[{'actions': [{'do': 'shell', 'cmd': push}]}, {}])
        self.run_cli('--once')
        self.assertEqual(self.calls('investigation')[0]['ctx']['commit'], pinned)
        self.assertEqual(self.state().checkpoint('owner/calc')['sha'], pinned)
        self.assertNotEqual(self.head(), pinned)
        self.run_cli('--once')
        self.assertEqual(self.calls('investigation')[1]['ctx']['commit'], self.head())

    def test_forced_rerun_of_unchanged_main(self):
        self.run_cli('--once')
        self.run_cli('--once')
        self.assertEqual(len(self.calls()), 1)
        self.assertEqual(self.run_cli('--repo', 'owner/calc', '--force'), 0)
        self.assertEqual(len(self.calls()), 2)
        self.assertEqual(self.calls()[1]['ctx']['changes']['mode'], 'unchanged')
        self.assertEqual(self.runs()[1]['forced'], 1)

    def test_disabled_repository_is_not_tested(self):
        self.run_cli('--once', repositories=[{'name': 'owner/calc', 'enabled': False}])
        self.assertEqual(self.calls(), [])
        self.assertEqual(self.runs(), [])

    def test_discovery_checkout_is_untouched(self):
        checkout = self.tmp / 'monitored-repos' / 'calc'
        before = sorted(p.relative_to(checkout) for p in checkout.rglob('*'))
        self.set_plan(investigation=[INVESTIGATE_FIX], fixing=[GOOD_FIX], verification=[GOOD_VERIFY])
        self.run_cli('--once')
        self.assertEqual(sorted(p.relative_to(checkout) for p in checkout.rglob('*')), before)
        self.assertNotEqual(self.calls()[0]['cwd'], str(checkout))


class BudgetTest(Case):
    def test_soft_budget_is_not_a_hard_kill_and_stops_new_work(self):
        slow = {'actions': [{'do': 'repro'}, {'do': 'sleep', 'seconds': 1.5}],
                'result': {'findings': [finding()], 'worth_continuing': True, 'overrun_reason': 'finishing repro'}}
        self.set_plan(investigation=[slow], fixing=[GOOD_FIX], verification=[{'actions': [{'do': 'verify_issue'}]}])
        self.run_cli('--once', soft_budget_minutes=0.01)
        self.assertEqual(len(self.calls('investigation')), 1)  # No new investigation after the target.
        self.assertEqual(self.calls('fixing'), [])  # No new fix after the target...
        self.assertEqual(len(self.calls('verification')), 1)  # ...but the confirmed finding is verified.
        [issue] = self.gh.created('issue')
        self.assertIn('soft time budget', issue['body'])
        self.assertIn('Soft budget overrun in investigation-1: finishing repro', self.log())
        self.assertEqual(self.runs()[0]['status'], 'completed')

    def test_investigation_continues_while_budget_remains(self):
        self.set_plan(investigation=[{'result': {'worth_continuing': True}}, {'result': {'worth_continuing': False}}])
        self.run_cli('--once')
        rounds = self.calls('investigation')
        self.assertEqual([c['ctx']['round'] for c in rounds], [1, 2])
        budget = rounds[0]['ctx']['budget']
        self.assertEqual(budget['soft_budget_minutes'], 20)
        self.assertTrue(budget['target_finish'].endswith(('+01:00', '+02:00')))
        self.assertLess(budget['stage_target'], budget['target_finish'])


class ProviderTest(Case):
    def test_stage_providers_models_and_overrides(self):
        codex = {'provider': 'codex', 'model': 'gpt-test', 'reasoning_effort': 'medium'}
        self.config['agents']['fixing'] = codex
        self.set_plan(investigation=[INVESTIGATE_FIX], fixing=[GOOD_FIX], verification=[GOOD_VERIFY])
        with mock.patch.dict(os.environ, {'ANTHROPIC_API_KEY': 'sk-ant-test', 'OPENAI_API_KEY': 'sk-test'}):
            self.run_cli('--once', repositories=[{'name': 'owner/calc', 'agents': {
                'verification': {'model': 'claude-verify', 'reasoning_effort': 'max'}}}])
        by_stage = {c['stage']: c for c in self.calls()}
        self.assertEqual({s: c['provider'] for s, c in by_stage.items()},
                         {'investigation': 'claude', 'fixing': 'codex', 'verification': 'claude'})
        fix_argv = by_stage['fixing']['argv']
        self.assertIn('gpt-test', fix_argv)
        self.assertIn('model_reasoning_effort="medium"', fix_argv)
        self.assertIn('forced_login_method="chatgpt"', fix_argv)
        verify_argv = by_stage['verification']['argv']
        self.assertEqual(verify_argv[verify_argv.index('--model') + 1], 'claude-verify')
        self.assertEqual(verify_argv[verify_argv.index('--effort') + 1], 'max')
        for call in self.calls():
            self.assertNotIn('--bare', call['argv'])
            self.assertNotIn('ANTHROPIC_API_KEY', call['env'])
            self.assertNotIn('OPENAI_API_KEY', call['env'])
        [pr] = self.gh.created('pr')
        self.assertTrue(pr['body'].startswith('## 🤖 Generated by Codex\n'))  # The fixer authored the patch.
        self.assertIn('verification claude `claude-verify` (max)', pr['body'])

    def test_claude_only_configuration_does_not_need_codex(self):
        (self.tmp / 'bin' / 'codex').unlink()
        self.assertEqual(self.run_cli('--once'), 0)
        self.assertEqual(self.runs()[0]['status'], 'completed')

    def test_missing_selected_provider_is_a_setup_blocker(self):
        (self.tmp / 'bin' / 'codex').unlink()
        self.config['agents']['fixing'] = {'provider': 'codex', 'model': 'gpt-test', 'reasoning_effort': 'low'}
        self.run_cli('--once')
        self.assertEqual(self.calls(), [])
        [issue] = self.gh.items['owner/auto-test']
        self.assertIn('codex agent setup', issue['title'])
        self.assertIn('not found', issue['body'])

    def test_api_key_login_is_rejected_not_used(self):
        self.set_plan(claude_auth={'loggedIn': True, 'authMethod': 'claude.ai', 'apiProvider': 'firstParty',
                                   'apiKeySource': 'ANTHROPIC_API_KEY'})
        self.run_cli('--once')
        self.assertEqual(self.calls(), [])
        self.assertIn('claude agent setup', self.gh.items['owner/auto-test'][0]['title'])
        self.assertIsNone(self.state().checkpoint('owner/calc'))

    def test_unsupported_codex_effort_is_rejected_clearly(self):
        self.config['agents']['fixing'] = {'provider': 'codex', 'model': 'gpt-test', 'reasoning_effort': 'xhigh'}
        self.run_cli('--once')
        self.assertEqual(self.calls(), [])
        self.assertIn('does not support reasoning_effort=xhigh', self.gh.items['owner/auto-test'][0]['body'])

    def test_authentication_failure_during_stage_blocks_without_checkpoint(self):
        self.set_plan(investigation=[{'error': 'auth'}])
        self.assertEqual(self.run_cli('--once'), 1)
        self.assertEqual(self.runs()[0]['status'], 'blocked')
        self.assertIsNone(self.state().checkpoint('owner/calc'))
        self.assertIn('claude agent setup', self.gh.items['owner/auto-test'][0]['title'])

    def test_malformed_output_is_incomplete_and_retried(self):
        self.set_plan(investigation=[{'error': 'malformed'}, {}])
        self.assertEqual(self.run_cli('--once'), 1)
        self.assertEqual(self.runs()[0]['status'], 'incomplete')
        self.assertIsNone(self.state().checkpoint('owner/calc'))
        self.assertEqual(self.run_cli('--once'), 0)
        self.assertEqual([r['status'] for r in self.runs()], ['incomplete', 'completed'])
        self.assertEqual(self.gh.created(), [])


class ExhaustionTest(Case):
    repos = ('owner/calc', 'owner/other')

    def test_exhausted_subscription_defers_without_looping(self):
        self.set_plan(investigation=[{'error': 'deferred'}])
        self.run_cli('--once')
        self.assertEqual(len(self.calls()), 1)  # The second repository is deferred, not attempted.
        self.assertEqual([r['status'] for r in self.runs()], ['incomplete'])
        self.assertEqual(self.gh.created(), [])
        self.assertIn('deferred', self.log())

    def test_same_blocker_in_two_repositories_is_one_issue(self):
        blocker = {'capability': 'Docker daemon', 'category': 'missing_tool', 'details': 'no docker',
                   'owner_action': 'Install Docker'}
        self.set_plan(investigation=[{'result': {'outcome': 'blocked', 'blockers': [blocker]}}])
        self.run_cli('--repo', 'owner/calc')
        [issue] = self.gh.created('issue')
        self.assertNotIn('owner/other', issue['body'])
        self.run_cli('--repo', 'owner/other')
        self.assertEqual(len(self.gh.created('issue')), 1)
        self.assertIn('update_issue', self.gh.calls)
        self.assertIn('owner/other', issue['body'])
        self.assertIn('owner/calc', issue['body'])


class OperationTest(Case):
    def test_dry_run_publishes_nothing_and_keeps_production_state(self):
        self.set_plan(investigation=[INVESTIGATE_FIX], fixing=[GOOD_FIX], verification=[GOOD_VERIFY])
        self.assertEqual(self.run_cli('--repo', 'owner/calc', '--force', '--dry-run'), 0)
        self.assertEqual([c for c in self.gh.calls if c != 'find_marker'], [])
        self.assertEqual(self.gh.created(), [])
        self.assertIsNone(self.state().checkpoint('owner/calc'))
        [report] = self.reports(dry_run=True)
        self.assertEqual((report['kind'], report['status']), ('pr', 'prepared'))
        run = self.runs(dry_run=True)[0]
        self.assertTrue((Path(run['directory']) / 'reports' / f'{report["key"]}.md').is_file())
        self.assertEqual(self.runs(), [])
        self.assertEqual(git(self.remotes['owner/calc'], 'branch', '--list', 'auto-test/*'), '')

    def test_overlapping_invocation_exits_without_agents(self):
        (self.tmp / 'var').mkdir()
        with open(self.tmp / 'var' / 'auto-test.lock', 'a') as handle:
            fcntl.flock(handle, fcntl.LOCK_EX | fcntl.LOCK_NB)
            self.assertEqual(self.run_cli('--once'), 0)
            self.assertEqual(self.run_cli('--repo', 'owner/calc', '--force', '--dry-run'), 0)
        self.assertEqual(self.calls(), [])
        self.assertIn('another invocation', self.log())

    def test_interruption_kills_agent_and_cleanup_retries_recorded_resources_only(self):
        self.set_plan(investigation=[{'actions': [{'do': 'create_resource'}, {'do': 'signal_parent'}]}, {}],
                      cleanup=[{'actions': [{'do': 'remove_resources'}]}])
        with self.assertRaises(KeyboardInterrupt):
            self.run_cli('--once')
        [run] = self.runs()
        self.assertEqual((run['status'], run['cleanup']), ('interrupted', 'pending'))
        pid = self.calls('investigation')[0]['pid']
        with self.assertRaises(ProcessLookupError):
            os.kill(pid, 0)
        self.assertFalse((Path(run['directory']) / 'workspace').exists())
        self.run_cli('--once')
        [cleanup] = self.calls('cleanup')
        self.assertEqual([r['name'] for r in cleanup['ctx']['unresolved_resources']], [f'auto-test-{run["id"]}'])
        self.assertEqual(self.state().run(run['id'])['cleanup'], 'clean')
        self.assertEqual([r['status'] for r in self.runs()], ['interrupted', 'completed'])

    def test_crashed_run_is_marked_interrupted_and_unresolved_cleanup_is_visible(self):
        self.set_plan(investigation=[{'actions': [{'do': 'create_resource'}]}], cleanup=[{}])
        self.run_cli('--once')  # Agent never removes the resource; cleanup stage fails to remove it.
        [run] = self.runs()
        self.assertEqual(run['cleanup'], 'pending')
        self.assertIn('unresolved test resources', self.gh.items['owner/auto-test'][0]['title'])
        self.sql("UPDATE runs SET status='running' WHERE id=?", run['id'])
        self.run_cli('--once')
        self.run_cli('--once')
        run = self.state().run(run['id'])
        self.assertEqual((run['status'], run['cleanup'], run['cleanup_attempts']), ('interrupted', 'failed', 3))
        self.assertEqual(len(self.calls('cleanup')), 3)
        output = self.status_output()
        self.assertIn('cleanup=failed', output)
        self.assertIn('Setup blocker: unresolved test resources', output)

    def status_output(self):
        self.assertEqual(self.run_cli('--status'), 0)
        return self.stdout

    def test_retention_removes_old_artifacts_but_keeps_identities(self):
        self.set_plan(investigation=[{'actions': [{'do': 'repro'}], 'result': {'findings': [finding(disposition='issue')]}}],
                      verification=[{'actions': [{'do': 'verify_issue'}]}])
        self.run_cli('--once')
        run = self.runs()[0]
        self.sql('UPDATE runs SET finished=?', time.time() - 40 * 86400)
        self.commit('owner/calc')
        self.set_plan()
        self.run_cli('--once')
        self.assertFalse(Path(run['directory']).exists())
        self.assertEqual(len(self.reports()), 1)
        self.assertEqual(self.state().checkpoint('owner/calc')['sha'], self.head())
